### ISSUE TITLE
验证成功以后就卡死在成功的状态了

### ISSUE THREAD

**Issue by wanliyunyan** [caijf/rc-slider-captcha#1]
比如用户验证成功了，但是其它的操作失败了，我需要用户再次验证，能不能开放一个手动刷新的接口，或者说我该怎么处理，因为失败了会自动刷新，成功了应该也要刷新才好吧

**Comment by caijf** [comment]
有考虑到这个场景，参考文档中的手动刷新，https://caijf.github.io/rc-slider-captcha/index.html#/#%E6%89%8B%E5%8A%A8%E5%88%B7%E6%96%B0

<img width="947" alt="image" src="https://user-images.githubusercontent.com/5070722/196585705-c2b4cef0-b95b-4571-95bc-5835fb71e1cb.png">

<img width="924" alt="image" src="https://user-images.githubusercontent.com/5070722/196585632-7ceb9fa6-83c8-4498-b781-375cda819e3f.png">

**Comment by wanliyunyan** [comment]
我这瞎子，竟然没看到......谢谢大佬
