### ISSUE TITLE
server side lib to get the image and puzzle

### ISSUE THREAD

**Issue by fabianbormann** [caijf/rc-slider-captcha#2]
Hey thanks for providing this great lib. :) Are you using any server side lib to generate the background image and the puzzle?

Thanks!

**Comment by caijf** [comment]
Thanks for your appreciation. I didn't use it. But you can refer to https://github.com/icjs-cc/itriton-captcha, or use canvas generation on the client side.

**Comment by fabianbormann** [comment]
Thanks I will look into this 😊

**Comment by caijf** [comment]
@fabianbormann Hi, I wrote a tool for generating puzzles on the client side.

https://caijf.github.io/create-puzzle/index.html#/generator

**Comment by fabianbormann** [comment]
Nice thx 😊
