### ISSUE TITLE
组件无法自适应

### ISSUE THREAD

**Issue by Monster-2019** [caijf/rc-slider-captcha#7]
![微信截图_20240726181937](https://github.com/user-attachments/assets/f2f89d3f-1932-403b-a7dd-559b9e36fbba)
![微信截图_20240726182013](https://github.com/user-attachments/assets/57d9e42e-c9a7-4136-86dc-4be83ff2277d)
组件无法自适应宽度，使用important强行对其，控件无法对齐。设置320px局限性太强了。建议宽度默认100%，onVerify内部实现是否验证成功即可。

**Comment by caijf** [comment]
配置发看看。
因为要计算可滑动距离，以及操作拼图和滑块的偏移值转换比，所以要通过 `bgSize` 和 `puzzleSize` 设置确定的尺寸。不建议在外部定义宽度，可能产生未知问题。

**Comment by caijf** [comment]
文档添加了纯滑块模式，宽度自适应示例，你可以参考下 [宽度自适应](https://caijf.github.io/rc-slider-captcha/index.html#/#%E5%AE%BD%E5%BA%A6%E8%87%AA%E9%80%82%E5%BA%94)。

<img width="589" alt="image" src="https://github.com/user-attachments/assets/b083be82-a993-4524-b8f1-04ca1ad8269b">
